version: '3'
services:
    postgres:
        image: postgres:15.0-alpine
        environment:
            PGUSER: 'postgres'
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 30s
            timeout: 10s
            retries: 5
    mysql:
        image: mysql:8
        environment:
            MYSQL_DATABASE: 'testdb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        command: --init-file /data/application/init.sql
        ports:
            - "3306:3306"
        healthcheck:
            test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - ./init.sql:/data/application/init.sql